name: Build and run Maestro tests (Native iOS)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up the correct version of Xcode (15.4)
      - name: Set up Xcode 15.4
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
          xcode-select -p  # Verify selected Xcode version

      # 3. Install dependencies
      - name: Install dependencies (CocoaPods)
        run: |
          brew install cocoapods
          pod install

      # 4. Build the app
      - name: Build the app (Debug configuration)
        run: |
          xcodebuild build -scheme 'MyApp' -configuration Debug -project 'MyApp.xcodeproj' -destination 'generic/platform=iOS Simulator' CONFIGURATION_BUILD_DIR=$PWD/build

      # 5. Upload app to Maestro Cloud for testing
      - name: Upload app to Maestro Cloud
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}  # Use your Maestro Cloud API key
          project-id: ${{ secrets.MAESTRO_PROJECT_ID }}  # Use your Maestro project ID
          app-file: build/MyApp.app  # Path to the built app file
          pullRequestId: ${{ github.event.pull_request.number }}  # Pull request ID
          commitSha: ${{ github.sha }}  # Commit hash
          branch: ${{ github.head_ref }}  # Pull request source branch