name: Build and Test with Maestro

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 安装 CocoaPods 依赖
      - name: Install dependencies with CocoaPods
        run: |
          gem install cocoapods
          pod install

      # 设置 Xcode 16.2 作为默认 Xcode 版本
      - name: Set Xcode 16.2
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
          xcodebuild -version

      # 构建项目
      - name: Build the app
        run: |
          xcodebuild build -scheme 'MyApp' -configuration Debug -project 'MyApp.xcodeproj' -destination 'generic/platform=iOS Simulator' CONFIGURATION_BUILD_DIR=$PWD/build

      # Maestro身份认证
      - name: Maestro authentication
        run: |
          echo ${{ secrets.MAESTRO_API_KEY }} > maestro_api_key.txt
          maestro-cli auth --api-key $(cat maestro_api_key.txt)

      # 上传到 Maestro Cloud
      - name: Upload to Maestro Cloud
        run: |
          maestro-cli upload --app-name "MyApp" --device "iPhone 16" --build-directory $PWD/build

      # 触发 Maestro 测试
      - name: Trigger Maestro Test
        run: |
          maestro-cli test --app-name "MyApp" --device "iPhone 16" --build-directory $PWD/build