name: Build and run Maestro tests (Native iOS)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Install cocoapods and dependencies
      - name: Install cocoapods
        run: |
          brew install cocoapods  # Ensure cocoapods is installed
          pod install             # Install dependencies from the Podfile

      # 3. Build the app
      - name: Build the app
        run: |
          xcodebuild build -scheme 'MyApp' -configuration Debug -project 'MyApp.xcodeproj' -destination 'generic/platform=iOS Simulator' CONFIGURATION_BUILD_DIR=$PWD/build

      # 4. Upload app file to Maestro Cloud for testing
      - name: Upload app to Maestro Cloud
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}  # Use your Maestro Cloud API key
          project-id: ${{ secrets.MAESTRO_PROJECT_ID }}  # Use your Maestro project ID
          app-file: build/MyApp.app  # Path to the built app file
          pullRequestId: ${{ github.event.pull_request.number }}  # Pull request ID
          commitSha: ${{ github.sha }}  # Commit hash
          branch: ${{ github.head_ref }}  # Pull request source branch