name: Build and Run Maestro Tests (Native iOS)

on:
  push:
    branches:
      - main  # 监听主分支的 push 事件
  pull_request:
    branches:
      - main  # 监听拉取请求的事件

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 安装依赖
      - name: Install dependencies
        run: |
          brew install cocoapods
          pod install

      # 构建项目
      - name: Build the app
        run: |
          xcodebuild build -scheme 'MyApp' -configuration Debug -project 'MyApp.xcodeproj' -destination 'generic/platform=iOS Simulator' CONFIGURATION_BUILD_DIR=$PWD/build

      # 上传到 Maestro Cloud
      - name: Upload app to Maestro Cloud
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}  # 你的 Maestro API 密钥
          project-id: ${{ secrets.MAESTRO_PROJECT_ID }}  # 你的 Maestro 项目 ID
          app-file: build/MyApp.app  # 你构建的应用文件路径
          pullRequestId: ${{ github.event.pull_request.number }}  # 如果是 PR 触发，使用 PR ID
          commitSha: ${{ github.sha }}  # 提交的哈希值
          branch: ${{ github.head_ref }}  # 触发 PR 时的源分支